variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

Unit Tests:
  stage: test
  image: python:3.6
  before_script:
    - pip install tox codecov
  script: tox -epy36
  after_script:
    - codecov

Flake8:
  stage: test
  image: python:3.6
  before_script:
    - pip install tox
  script: tox -eflake8

Build Container:
  stage: test
  except:
    - master
    - tags
  image: docker
  services:
    - docker:dind
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest .

Build and Push Container:
  stage: deploy
  image: docker
  only:
    - master
    - tags
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE:latest