sudo: false
language: python
cache: pip

stages:
  - test
  - name: build and push container
    if: (type IN (push)) AND ((branch = master) OR (tag IS present))

jobs:
  include:
    - stage: test
      python: 3.6
      install: pip install tox codecov
      script: tox -epy36
      after_success: codecov
    - stage: test
      python: 3.6
      install: pip install tox
      script: tox -eflake8
    - stage: test
      if: (branch != master AND tag IS blank) OR (type IN (pull_request))
      services: docker
      sudo: required
      script:
        - docker build .
    - stage: build and push container
      services: docker
      sudo: required
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - if [ $TRAVIS_BRANCH == "master" ]; then
            docker build -t cloudigrade/houndigrade:latest .;
          else
            docker build -t cloudigrade/houndigrade:$TRAVIS_TAG .;
          fi
        - docker push cloudigrade/houndigrade
