version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      - QUEUE_CONNECTION_URL
      - RESULTS_QUEUE_NAME=${AWS_SQS_QUEUE_NAME_PREFIX}inspection_results
    volumes:
      - ./docker/dev-entrypoint.sh:/opt/houndigrade/entrypoint.sh
      - ./docker/rh_disk:/dev/rh_disk
      - ./docker/nrh_disk:/dev/nrh_disk
      - ./docker/both_disk:/dev/both_disk
      - /dev:/dev
    privileged: true
