version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - EXCHANGE_NAME
      - QUEUE_CONNECTION_URL
      - RESULTS_QUEUE_NAME=${AWS_SQS_QUEUE_NAME_PREFIX}inspection_results
    volumes:
      - ./docker/dev-entrypoint.sh:/opt/houndigrade/entrypoint.sh
      - ./test-data:/test-data:ro
      - /dev:/dev
    privileged: true
