version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    environment:
      - RESULTS_BUCKET_NAME=${CLOUDIGRADE_ENVIRONMENT}-cloudigrade-inspections
    volumes:
      - ./docker/dev-entrypoint.sh:/opt/houndigrade/entrypoint.sh
      - ./test-data:/test-data:ro
      - /dev:/dev
    privileged: true
