name: Push

env:
  IMAGE_NAME: quay.io/cloudservices/houndigrade
  IMAGE_NAME_COMMIT: quay.io/cloudservices/houndigrade:${{ github.sha }}

on: [push]

jobs:
  test-py39:
    name: py39
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox codecov poetry
      - run: tox -e py39
      - run: codecov

  test-flake8:
    name: flake8
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox poetry
      - run: tox -e flake8
