name: Push

env:
  IMAGE_NAME: quay.io/cloudservices/houndigrade
  IMAGE_NAME_COMMIT: quay.io/cloudservices/houndigrade:${{ github.sha }}

on: [push]

jobs:
  test-py38:
    name: py38
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox codecov poetry
      - run: tox -e py38
      - run: codecov

  test-flake8:
    name: flake8
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox poetry
      - run: tox -e flake8

  test-docker:
    name: Docker Build
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from $IMAGE_NAME:latest .

  deploy-build-and-push-image:
    name: Build and Push Image
    if: github.ref == 'refs/heads/master'
    needs: [test-py38, test-flake8, test-docker]
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    env:
      QUAY_BOT_USERNAME: ${{ secrets.QUAY_BOT_USERNAME }}
      QUAY_BOT_TOKEN: ${{ secrets.QUAY_BOT_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - run: echo "${QUAY_BOT_TOKEN}" | docker login quay.io -u ${QUAY_BOT_USERNAME} --password-stdin
      - run: docker pull $IMAGE_NAME:latest || true
      - run: docker build --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME_COMMIT} --tag ${IMAGE_NAME}:latest .
      - run: docker push ${IMAGE_NAME_COMMIT}
      - run: docker push ${IMAGE_NAME}:latest

